- name: Prepare all Kubernetes nodes
	hosts: k8s_all
	become: yes
	vars:
		k8s_version: "1.28.5"
	tasks:
		- name: Disable swap
			ansible.builtin.shell: |
				swapoff -a
				sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
		- name: Load kernel modules
			ansible.builtin.shell: |
				cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
				overlay
				br_netfilter
				EOF
				modprobe overlay
				modprobe br_netfilter
		- name: Configure sysctl params
			ansible.builtin.shell: |
				cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
				net.bridge.bridge-nf-call-iptables = 1
				net.bridge.bridge-nf-call-ip6tables = 1
				net.ipv4.ip_forward = 1
				EOF
				sysctl --system
		- name: Install required packages
			package:
				name:
					- apt-transport-https
					- ca-certificates
					- curl
					- gnupg
					- lsb-release
				state: present
