---
- name: Setup kubectl on control node
  hosts: control
  become: yes
  vars:
    k8s_version: "1.28.15"  # Синхронизировано с предыдущими файлами
  tasks:
    - name: Create .kube directory for root user
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy admin config from master node
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        flat: yes
      delegate_to: "{{ groups['k8s_master'][0] }}"

    - name: Set correct ownership and permissions for config
      ansible.builtin.file:
        path: /root/.kube/config
        owner: root
        group: root
        mode: '0600'
