---
- name: Setup kubectl access on ansible-control node
  hosts: k8s_master
  become: yes
  tasks:
    - name: Check if admin.conf exists on master
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: admin_conf_stat

    - name: Fail if admin.conf is missing
      ansible.builtin.fail:
        msg: "File /etc/kubernetes/admin.conf not found on k8s-master-01. Please verify its existence and permissions."
      when: not admin_conf_stat.stat.exists

    - name: Create .kube directory for adminskv
      ansible.builtin.file:
        path: /home/adminskv/.kube
        state: directory
        owner: adminskv
        group: adminskv
        mode: '0755'
      delegate_to: "{{ groups['control'][0] }}"
      become: yes
      become_user: root

    - name: Copy kubeconfig to ansible-control node
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: /home/adminskv/.kube/config
        flat: yes
      delegate_to: "{{ groups['control'][0] }}"
      become: yes
      become_user: root

    - name: Update kubeconfig with master node IP
      ansible.builtin.replace:
        path: /home/adminskv/.kube/config
        regexp: 'server: https://127.0.0.1:6443'
        replace: "server: https://{{ hostvars['k8s-master-01']['ansible_default_ipv4']['address'] }}:6443"
      delegate_to: "{{ groups['control'][0] }}"

    - name: Set correct permissions on kubeconfig
      ansible.builtin.file:
        path: /home/adminskv/.kube/config
        owner: adminskv
        group: adminskv
        mode: '0600'
      delegate_to: "{{ groups['control'][0] }}"

    - name: Install kubectl on ansible-control node
      package:
        name: kubectl
        state: present
      delegate_to: "{{ groups['control'][0] }}"
      become: yes
      become_user: root

    - name: Verify kubectl access
      ansible.builtin.shell: |
        kubectl get nodes
      register: kubectl_nodes
      delegate_to: "{{ groups['control'][0] }}"
      become: yes
      become_user: adminskv  # Проверяем от имени adminskv

    - name: Display nodes info
      ansible.builtin.debug:
        msg: "{{ kubectl_nodes.stdout }}"
