---
- name: Setup kubectl access on ansible-control node
  hosts: k8s_master
  become: yes
  vars:
    ansible_user: adminskv
    ansible_become: yes
    ansible_become_user: root
    ansible_become_method: sudo
  tasks:
    - name: Check if admin.conf exists on master
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: admin_conf_stat
      become: yes
      become_user: root

    - name: Fail if admin.conf is missing
      ansible.builtin.fail:
        msg: "File /etc/kubernetes/admin.conf not found on k8s-master-01. Please verify its existence or rerun 02_init_master.yml or perform 'kubeadm init'. Current path check: {{ admin_conf_stat.stat.path }}, exists: {{ admin_conf_stat.stat.exists }}"
      when: not admin_conf_stat.stat.exists

    - name: Debug file details
      ansible.builtin.debug:
        msg: "File exists: {{ admin_conf_stat.stat.exists }}, path: {{ admin_conf_stat.stat.path }}, readable: {{ admin_conf_stat.stat.readable }}, mode: {{ admin_conf_stat.stat.mode }}"
      when: admin_conf_stat.stat.exists

    - name: Stop Kubernetes services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - kubelet
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
        - etcd
      ignore_errors: yes

    - name: Remove Kubernetes manifests
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes/manifests/kube-apiserver.yaml
        - /etc/kubernetes/manifests/kube-controller-manager.yaml
        - /etc/kubernetes/manifests/kube-scheduler.yaml
        - /etc/kubernetes/manifests/etcd.yaml
      ignore_errors: yes

    - name: Remove etcd data
      ansible.builtin.file:
        path: /var/lib/etcd
        state: absent
      ignore_errors: yes

    - name: Reset kubeadm
      ansible.builtin.command: kubeadm reset -f
      ignore_errors: yes

    - name: Create .kube directory for root
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        owner: root
        group: root
        mode: '0755'
      delegate_to: "{{ groups['control'][0] }}"
      become: yes
      become_user: root

    - name: Accept SSH host key for ansible-control
      ansible.builtin.command: ssh-keyscan -H {{ hostvars[groups['control'][0]]['ansible_host'] }} >> ~/.ssh/known_hosts
      args:
        creates: ~/.ssh/known_hosts
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Test SSH connectivity to ansible-control
      ansible.builtin.command: ssh -o BatchMode=yes root@{{ hostvars[groups['control'][0]]['ansible_host'] }} "echo Connection successful"
      register: ssh_test
      failed_when: ssh_test.rc != 0
      timeout: 30

    - name: Debug SSH test result
      ansible.builtin.debug:
        msg: "SSH test output: {{ ssh_test.stdout }}"
      when: ssh_test.rc == 0

    - name: Create temporary copy of admin.conf with readable permissions
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/admin.conf
        remote_src: yes
        mode: '0644'
        owner: root
        group: root
      become: yes
      become_user: root

    - name: Debug temporary file details
      ansible.builtin.stat:
        path: /tmp/admin.conf
      register: temp_stat
      become: yes
      become_user: root

    - name: Debug temp file permissions
      ansible.builtin.debug:
        msg: "Temp file exists: {{ temp_stat.stat.exists }}, path: {{ temp_stat.stat.path }}, readable: {{ temp_stat.stat.readable }}, mode: {{ temp_stat.stat.mode }}, owner: {{ temp_stat.stat.pw_name }}"
      when: temp_stat.stat.exists

    - name: Copy admin.conf to ansible-control using scp
      ansible.builtin.command: scp /tmp/admin.conf root@{{ hostvars[groups['control'][0]]['ansible_host'] }}:/root/.kube/config
      become: yes
      become_user: root
      register: scp_result
      retries: 3
      delay: 5
      until: scp_result.rc == 0

    - name: Remove temporary copy of admin.conf
      ansible.builtin.file:
        path: /tmp/admin.conf
        state: absent
      become: yes
      become_user: root
      when: scp_result.changed

    - name: Update kubeconfig with master node IP
      ansible.builtin.replace:
        path: /root/.kube/config
        regexp: 'server: https://127.0.0.1:6443'
        replace: "server: https://{{ hostvars['k8s-master-01']['ansible_default_ipv4']['address'] }}:6443"
      delegate_to: "{{ groups['control'][0] }}"
      when: scp_result.changed

    - name: Set correct permissions on kubeconfig
      ansible.builtin.file:
        path: /root/.kube/config
        owner: root
        group: root
        mode: '0600'
      delegate_to: "{{ groups['control'][0] }}"
      when: scp_result.changed

    - name: Install kubectl on ansible-control node
      package:
        name: kubectl
        state: present
      register: kubectl_install
      delegate_to: "{{ groups['control'][0] }}"
      become: yes
      become_user: root
      retries: 3
      delay: 5
      until: not kubectl_install.failed
      failed_when: kubectl_install.failed

    - name: Debug kubectl install result
      ansible.builtin.debug:
        msg: "kubectl install result: {{ kubectl_install }}"
      when: kubectl_install.failed

    - name: Check API server connectivity
      ansible.builtin.command: curl -k https://{{ hostvars['k8s-master-01']['ansible_default_ipv4']['address'] }}:6443
      register: api_check
      delegate_to: "{{ groups['control'][0] }}"
      become: yes
      become_user: root
      ignore_errors: yes

    - name: Debug API server connectivity
      ansible.builtin.debug:
        msg: "API server check: {{ api_check.rc }}, output: {{ api_check.stdout }}"
      delegate_to: "{{ groups['control'][0] }}"
      become: yes
      become_user: root

    - name: Verify API server is running on master
      ansible.builtin.command: systemctl status kube-apiserver
      register: api_status
      become: yes
      become_user: root
      ignore_errors: yes

    - name: Debug API server status
      ansible.builtin.debug:
        msg: "API server status: {{ api_status.rc }}, output: {{ api_status.stdout }}"
      become: yes
      become_user: root

    - name: Fail if API server is not running
      ansible.builtin.fail:
        msg: "kube-apiserver is not running on k8s-master-01. Please ensure 'kubeadm init' has been run successfully. Output: {{ api_status.stdout }}"
      when: api_status.rc != 0

    - name: Verify kubectl access
      ansible.builtin.shell: |
        kubectl get nodes
      register: kubectl_nodes
      delegate_to: "{{ groups['control'][0] }}"
      become: yes
      become_user: root
      retries: 3
      delay: 5
      until: kubectl_nodes.rc == 0
      failed_when: kubectl_nodes.rc != 0

    - name: Display nodes info
      ansible.builtin.debug:
        msg: "{{ kubectl_nodes.stdout }}"
