---
- name: Join worker nodes to Kubernetes cluster
  hosts: k8s_workers
  become: yes
  vars:
    ansible_user: adminskv
    ansible_become: yes
    ansible_become_user: root
    ansible_become_method: sudo
    kubeadm_join_command: "kubeadm join 192.168.1.138:6443 --token y00b4t.7fxpthwwwgc4r21g --discovery-token-ca-cert-hash sha256:c0f7656f6e610baa22b9466894279904af0f2eab7ab086de25a403dc28911db6"
  tasks:
    - name: Install Kubernetes components on worker nodes
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - kubeadm
        - kubelet
        - kubectl
      become: yes
      become_user: root

    - name: Hold Kubernetes packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        install_recommends: no
      loop:
        - kubeadm
        - kubelet
        - kubectl
      register: hold_result
      become: yes
      become_user: root

    - name: Join node to Kubernetes cluster
      ansible.builtin.command: "{{ kubeadm_join_command }}"
      register: join_result
      retries: 3
      delay: 5
      until: join_result.rc == 0
      failed_when: join_result.rc != 0

    - name: Debug join result
      ansible.builtin.debug:
        msg: "Join result: {{ join_result.rc }}, output: {{ join_result.stdout }}"
      when: join_result.rc == 0
